spring:
  config:
    activate:
      on-profile: dev
  application:
    name: jpaDemo

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  #    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:postgresql://localhost:5432/${DB_TABLE}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  #    password: ENC(DET7+SRjKW3/5Mbyh1aUNV2l4w7pwpog7yBMdRtCk1c0mZs805g8Zd6hNEhJgnrR)

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  lifecycle:
    timeout-per-shutdown-phase: 10s

# swagger
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true

#jasypt:
#  encryptor:
#    password: ${JASYPT_KEY}

server:
  shutdown: graceful