spring:
  application:
    name: jpaDemo

  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
  #    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#    url: jdbc:postgresql://localhost:5432/${DB_TABLE}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
  #    password: ENC(DET7+SRjKW3/5Mbyh1aUNV2l4w7pwpog7yBMdRtCk1c0mZs805g8Zd6hNEhJgnrR)

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

# swagger
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true
    url: "https://jpademo-production.up.railway.app/v3/api-docs"

#jasypt:
#  encryptor:
#    password: ${JASYPT_KEY}

server:
  shutdown: graceful

